name: flutter_gofast
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

#flutter packages pub run build_runner build --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter
  # Localização e idioma
  flutter_localizations:
    sdk: flutter
  # Rotas, Injeção de Dependencia
  flutter_modular: ^2.0.1
  # Gerencia de Estado
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0
  # Local Storage
  shared_preferences: ^0.5.6+3
  # Firebase
  firebase_core: ^0.4.4
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.4.4
  #Camera
  image_picker: ^0.6.3
  path_provider: ^1.6.24
  path: ^1.7.0
  firebase_storage: 3.1.6
  
  # Icones Cupertino
  cupertino_icons: ^0.1.2
  #Pacote de icones https://feathericons.com/
  flutter_icons: ^1.1.0
  barcode_scan: ^2.0.2
  http: ^0.12.0+1
  #Provider
  provider: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.3
  build_runner:
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
      - family: Google
        fonts:
          - asset: assets/fonts/ProductSans-Regular.ttf
          - asset: assets/fonts/ProductSans-Bold.ttf
            weight: 700 
